from .myThymio import MyThymio
from .thymio_constants import (WHEELS_SPACING, THYMIO_SPEED_TO_MMS, MMS_TO_THYMIO_SPEED, SENSOR_FORWARD_OFFSET,
                               SENSOR_PERP_OFFSET, GROUND_THRESHOLD, LOCAL_AVOIDANCE_DISTANCE_THRESHOLD,
                               WAYPOINT_REACHED_THRESHOLD_MM, OBSTACLE_DISTANCE_THRESHOLD_MM, AVOIDANCE_DISTANCE_MM)
