WHEELS_SPACING = 50

THYMIO_SPEED_TO_MMS = 0.36

MMS_TO_THYMIO_SPEED = 1 / THYMIO_SPEED_TO_MMS

SENSOR_FORWARD_OFFSET = 70

SENSOR_PERP_OFFSET = 10

GROUND_THRESHOLD = 500

LOCAL_AVOIDANCE_DISTANCE_THRESHOLD = 100

WAYPOINT_REACHED_THRESHOLD_MM = 25

OBSTACLE_DISTANCE_THRESHOLD_MM = 100

AVOIDANCE_DISTANCE_MM = 55
